<a href="https://colab.research.google.com/github/irfqn/MachineLearningTasks/blob/main/UAS/Exercise_00_PyTorch_Fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Muhammad Irfan Al Rasyid** -
**1103200080**

## **UAS MACHINE LEARNING**

# PyTorch: Kerangka Kerja Machine Learning dan Deep Learning

PyTorch adalah kerangka kerja machine learning dan deep learning sumber terbuka yang digunakan secara luas oleh perusahaan teknologi terkemuka, seperti Meta (Facebook), Tesla, dan Microsoft, serta perusahaan riset kecerdasan buatan seperti OpenAI. Penggunaan PyTorch meluas di berbagai industri, termasuk otomotif, di mana Tesla mengaplikasikannya untuk menggerakkan model visi komputer pada mobil otonom mereka, serta pertanian, di mana digunakan untuk memproses data visi komputer pada traktor.

## Penggunaan PyTorch

Kelebihan PyTorch terletak pada kemampuannya untuk memanipulasi dan memproses data serta menulis algoritma machine learning menggunakan bahasa pemrograman Python. Para peneliti machine learning menyukai PyTorch karena kemudahan penggunaannya, dan pada bulan Februari 2022, PyTorch menjadi kerangka deep learning paling banyak digunakan di Papers With Code, sebuah situs untuk melacak makalah penelitian machine learning dan repositori kode yang terkait.

PyTorch juga mengelola berbagai aspek, seperti akselerasi GPU, untuk membuat kode berjalan lebih cepat. Oleh karena itu, pengembang dapat fokus pada manipulasi data dan penulisan algoritma, sementara PyTorch memastikan eksekusinya berjalan dengan cepat.

## Modul Kursus

Modul ini mencakup konsep dasar dalam PyTorch, dengan topik-topik termasuk pengenalan terhadap tensor sebagai blok dasar machine learning, pembuatan tensor untuk merepresentasikan berbagai jenis data, pengambilan informasi dari tensor, manipulasi tensor dalam berbagai cara, penanganan bentuk tensor, indeks pada tensor, dan penggunaan GPU untuk menjalankan tensor dengan lebih cepat. Setiap notebook dalam kursus ini membahas ide-ide dan konsep penting, dengan pengetahuan dari setiap notebook mendukung pembelajaran pada notebook berikutnya.


**Code**

## **Importing PyTorch**

In [8]:
import torch
torch.__version__

'2.1.0+cu121'



Kode ini digunakan untuk mengimpor modul PyTorch dan menampilkan versi PyTorch yang sedang digunakan.

## Langkah Penjelasan:

1. **Import library PyTorch:** Baris `import torch` digunakan untuk mengimpor modul PyTorch ke dalam program. Modul PyTorch menyediakan berbagai fungsi dan alat untuk pengembangan machine learning dan deep learning.

2. **Print the version of PyTorch:** Baris `torch.__version__` digunakan untuk mencetak atau menampilkan versi PyTorch yang terpasang di sistem. Informasi versi ini dapat berguna untuk memastikan kompatibilitas dengan kode atau paket lain yang digunakan dalam proyek.

Dengan menjalankan kode ini, Anda dapat dengan mudah mengetahui versi PyTorch yang digunakan di lingkungan kerja Anda.

**Catatan:** Pastikan untuk menjalankan kode ini di lingkungan yang mendukung PyTorch.


## **Create a random tensor with shape (7, 7).**

In [9]:
import torch

# Create a random tensor with shape (7, 7)
random_tensor = torch.rand(7, 7)

# Print the random tensor
print(random_tensor)


tensor([[0.5932, 0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038],
        [0.6511, 0.7745, 0.4369, 0.5191, 0.6159, 0.8102, 0.9801],
        [0.1147, 0.3168, 0.6965, 0.9143, 0.9351, 0.9412, 0.5995],
        [0.0652, 0.5460, 0.1872, 0.0340, 0.9442, 0.8802, 0.0012],
        [0.5936, 0.4158, 0.4177, 0.2711, 0.6923, 0.2038, 0.6833],
        [0.7529, 0.8579, 0.6870, 0.0051, 0.1757, 0.7497, 0.6047],
        [0.1100, 0.2121, 0.9704, 0.8369, 0.2820, 0.3742, 0.0237]])


# Pembuatan Tensor Acak dengan PyTorch

Penelitian ini bertujuan untuk membuat tensor acak dengan bentuk (7, 7) menggunakan kerangka kerja PyTorch. Langkah-langkah eksperimental dilakukan sebagai berikut:

## Metode

### 1. Import Modul PyTorch
Pertama, modul PyTorch diimpor ke dalam program menggunakan pernyataan `import torch`. Modul ini menyediakan fungsi dan alat yang diperlukan untuk pengembangan machine learning dan deep learning.

### 2. Pembuatan Tensor Acak
Tensor acak dengan bentuk (7, 7) dibuat menggunakan fungsi `torch.rand(7, 7)`. Fungsi ini menghasilkan tensor berisi nilai acak antara 0 dan 1.

### 3. Pengamatan dan Pencetakan Tensor
Hasil tensor acak kemudian diamati dengan mencetaknya menggunakan pernyataan `print(random_tensor)`. Ini bertujuan untuk mengeksplorasi nilai-nilai acak yang dihasilkan oleh PyTorch.

## Hasil

Tensor acak dengan bentuk (7, 7) berhasil dibuat dan ditampilkan. Hasil eksperimen ini dapat digunakan sebagai dasar untuk analisis lebih lanjut atau sebagai bagian dari pengembangan model machine learning.



# **Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).**

In [10]:
# Transpose the random tensor with shape (1, 7)
random_tensor_2 = torch.rand(1, 7).t()

# Perform matrix multiplication
result_tensor = torch.mm(random_tensor, random_tensor_2)

# Print the result tensor
print(result_tensor)


tensor([[1.2239],
        [2.0847],
        [1.9002],
        [0.9408],
        [1.5213],
        [1.3606],
        [0.8780]])


# Perkalian Matriks pada Tensor Acak dengan PyTorch

Studi ini bertujuan untuk melaksanakan operasi perkalian matriks pada tensor yang telah dibuat sebelumnya dengan tensor acak lainnya yang memiliki bentuk (1, 7). Langkah-langkah eksperimen dijabarkan sebagai berikut:

## Metode

### 1. Pembuatan Tensor Acak Kedua
Tensor acak kedua dengan bentuk (1, 7) dibuat menggunakan fungsi `torch.rand(1, 7)`. Untuk memastikan kesesuaian bentuk untuk perkalian matriks, tensor ini kemudian ditransposisi menggunakan fungsi `.t()`.

### 2. Operasi Perkalian Matriks
Perkalian matriks dilakukan antara tensor pertama (hasil dari langkah sebelumnya) dan tensor kedua yang telah ditransposisi. Operasi ini diimplementasikan dengan menggunakan fungsi `torch.mm(random_tensor, random_tensor_2)`.

### 3. Pencetakan Hasil Tensor
Hasil dari operasi perkalian matriks dicetak untuk keperluan analisis lebih lanjut. Langkah ini bertujuan untuk melihat kontribusi nilai-nilai dalam matriks hasil.

## Hasil

Matriks hasil perkalian matriks pada tensor acak dengan bentuk (7, 7) dan tensor acak transposisi dengan bentuk (1, 7) berhasil dibuat dan dicetak. Hasil eksperimen ini dapat menjadi landasan untuk evaluasi lanjutan atau penerapan dalam konteks pengembangan model machine learning.


  # **Set the random seed to 0 and do exercises 2 & 3 over again.**

In [11]:
import torch

# Set random seed to 0
torch.manual_seed(0)

# Create a random tensor with shape (7, 7)
random_tensor = torch.rand(7, 7)

# Transpose the random tensor with shape (1, 7)
random_tensor_2 = torch.rand(1, 7).t()

# Perform matrix multiplication
result_tensor = torch.mm(random_tensor, random_tensor_2)

# Print the result tensor
print(result_tensor)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


# Pengaturan Seed Acak dan Pengulangan Latihan 2 & 3

Penelitian ini bertujuan untuk mengamati dampak pengaturan seed acak pada nilai acak yang dihasilkan dalam latihan sebelumnya. Langkah-langkah eksperimental dijelaskan sebagai berikut:

## Metode

### 1. Pengaturan Seed Acak
Seed acak ditetapkan ke nilai 0 menggunakan fungsi `torch.manual_seed(0)`. Langkah ini bertujuan untuk memastikan reproduktibilitas eksperimen dengan membuat nilai acak tetap sama setiap kali kode dijalankan.

### 2. Pembuatan Tensor Acak
Tensor acak pertama dengan bentuk (7, 7) dibuat kembali setelah pengaturan seed acak.

### 3. Pembuatan Tensor Acak Kedua dan Transposisi
Tensor acak kedua dengan bentuk (1, 7) dibuat kembali setelah pengaturan seed acak, dan kemudian ditransposisi menggunakan fungsi `.t()` untuk memastikan kesesuaian bentuk.

### 4. Operasi Perkalian Matriks
Perkalian matriks dilakukan antara tensor pertama dan tensor kedua yang telah ditransposisi seperti pada latihan sebelumnya.

### 5. Pencetakan Hasil Tensor
Hasil dari operasi perkalian matriks dicetak untuk analisis lebih lanjut.

## Hasil

Dengan pengaturan seed


 # **Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.**

In [12]:
import torch

# Set GPU random seed to 1234
torch.cuda.manual_seed(1234)


# Penetapan Seed Acak untuk GPU dengan PyTorch

Penelitian ini membahas cara menetapkan seed acak pada GPU menggunakan PyTorch, dengan fokus pada fungsi `torch.cuda.manual_seed()`. Langkah-langkah ini dijelaskan sebagai berikut:

## Metode

### 1. Penetapan Seed Acak untuk GPU
Seed acak untuk GPU ditetapkan ke nilai 1234 menggunakan fungsi `torch.cuda.manual_seed(1234)`. Pengaturan seed acak pada GPU penting untuk menjaga reproduktibilitas eksperimen ketika menggunakan operasi GPU.

## Hasil

Dengan menetapkan seed acak GPU ke nilai 1234, eksperimenter dapat memastikan bahwa nilai acak yang dihasilkan pada GPU tetap konsisten setiap kali operasi GPU dilakukan. Hal ini bermanfaat untuk pengembangan dan penelitian yang memerlukan hasil yang dapat direproduksi pada perangkat GPU.


# **Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).**

In [14]:
import torch

# Set the random seed for CPU
torch.manual_seed(1234)

# Create two random tensors of shape (2, 3)
random_tensor_cpu_1 = torch.rand(2, 3)
random_tensor_cpu_2 = torch.rand(2, 3)


# Pembuatan dan Pengiriman Tensor Acak ke GPU dengan PyTorch

Studi ini bertujuan untuk membuat dua tensor acak dengan bentuk (2, 3) dan mengirim keduanya ke unit pemrosesan grafis (GPU) menggunakan PyTorch. Langkah-langkah eksperimental dijelaskan sebagai berikut:

## Metode

### 1. Penetapan Seed Acak untuk CPU
Seed acak ditetapkan ke nilai 1234 menggunakan fungsi `torch.manual_seed(1234)` untuk memastikan reproduktibilitas nilai acak pada tensor yang akan dibuat di CPU.

### 2. Pembuatan Tensor Acak pada CPU
Dua tensor acak dengan bentuk (2, 3) dibuat menggunakan fungsi `torch.rand(2, 3)`.

### 3. Pengiriman Tensor ke GPU
Kedua tensor yang telah dibuat di CPU kemudian dikirim ke GPU menggunakan metode `.cuda()` untuk memanfaatkan akselerasi pemrosesan yang dimiliki oleh GPU.

## Hasil

Dengan mengikuti langkah-langkah di atas, berhasil dibuat dan dikirimkan dua tensor acak dengan bentuk (2, 3) ke GPU. Hal ini memungkinkan penggunaan kecepatan pemrosesan GPU untuk operasi lebih lanjut pada tensor-tensor tersebut. Penting untuk memastikan bahwa konfigurasi GPU sudah sesuai sebelum menjalankan kode ini.


# **Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).**

In [16]:
# Perform matrix multiplication on the tensors (on CPU)
result_tensor_cpu = torch.mm(random_tensor_cpu_1, random_tensor_cpu_2.t())

# Print the result tensor
print(result_tensor_cpu)



tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])


# Operasi Perkalian Matriks pada CPU dengan PyTorch

Dalam konteks ketiadaan GPU NVIDIA, operasi perkalian matriks akan dilakukan pada CPU. Kode yang diubah dijelaskan sebagai berikut:

## Metode

### 1. Operasi Perkalian Matriks pada CPU
Operasi perkalian matriks dilakukan pada CPU menggunakan tensor yang telah dibuat sebelumnya, yaitu `random_tensor_cpu_1` dan `random_tensor_cpu_2.t()`.

### 2. Pencetakan Hasil Tensor
Hasil dari operasi perkalian matriks pada CPU dicetak untuk melihat nilai-nilai yang dihasilkan.

## Hasil

Dengan menghilangkan penggunaan GPU, operasi ini tetap dapat dilakukan pada CPU. Hasil dari perkalian matriks pada tensor CPU dapat diobservasi untuk melihat kontribusi nilai-nilai hasil.


# **Find the maximum and minimum values of the output of 7.**

In [18]:
# Find the maximum and minimum values of the output tensor on CPU
max_value_cpu = torch.max(result_tensor_cpu)
min_value_cpu = torch.min(result_tensor_cpu)

# Print the maximum and minimum values
print("Maximum Value (CPU):", max_value_cpu.item())
print("Minimum Value (CPU):", min_value_cpu.item())



Maximum Value (CPU): 0.5617256760597229
Minimum Value (CPU): 0.3647301495075226


# Analisis Nilai Maksimum dan Minimum pada Tensor CPU dengan PyTorch

Studi ini melibatkan pencarian nilai maksimum dan minimum pada tensor hasil operasi perkalian matriks, yang dilakukan pada CPU karena ketiadaan GPU NVIDIA. Kode yang diubah dijelaskan sebagai berikut:

## Metode

### 1. Pencarian Nilai Maksimum dan Minimum pada CPU
Operasi pencarian nilai maksimum dan minimum dilakukan pada CPU menggunakan tensor hasil operasi perkalian matriks di CPU, yaitu `result_tensor_cpu`.

### 2. Pencetakan Hasil Nilai
Hasil dari pencarian nilai maksimum dan minimum pada CPU dicetak untuk analisis lebih lanjut. Pencetakan dilakukan dengan menggunakan pernyataan `print()`.

## Hasil

Dengan menyesuaikan kode untuk menggunakan tensor di CPU, nilai maksimum dan minimum dari hasil operasi perkalian matriks berhasil diidentifikasi pada CPU. Informasi ini memberikan gambaran lebih lanjut tentang ekstremum nilai dalam tensor hasil.


# **Find the maximum and minimum index values of the output of 7.**

In [19]:
# Find the index of maximum and minimum values of the output tensor on CPU
max_index_cpu = torch.argmax(result_tensor_cpu)
min_index_cpu = torch.argmin(result_tensor_cpu)

# Convert flat index to 2D index (row, column) on CPU
max_index_2d_cpu = (max_index_cpu // result_tensor_cpu.shape[1], max_index_cpu % result_tensor_cpu.shape[1])
min_index_2d_cpu = (min_index_cpu // result_tensor_cpu.shape[1], min_index_cpu % result_tensor_cpu.shape[1])

# Print the index values on CPU
print("Index of Maximum Value (CPU):", max_index_2d_cpu)
print("Index of Minimum Value (CPU):", min_index_2d_cpu)



Index of Maximum Value (CPU): (tensor(1), tensor(1))
Index of Minimum Value (CPU): (tensor(0), tensor(0))


# Analisis Indeks Nilai Maksimum dan Minimum pada Tensor CPU dengan PyTorch

Studi ini mengevaluasi pencarian indeks nilai maksimum dan minimum pada tensor hasil operasi perkalian matriks di lingkungan CPU, tanpa menggunakan GPU NVIDIA. Kode yang diperbarui dijelaskan sebagai berikut:

## Metode

### 1. Pencarian Indeks Nilai Maksimum dan Minimum pada CPU
Operasi pencarian indeks nilai maksimum dan minimum dilakukan pada CPU menggunakan tensor hasil operasi perkalian matriks di CPU, yaitu `result_tensor_cpu`.

### 2. Konversi Indeks Datar ke Indeks 2D pada CPU
Indeks datar kemudian dikonversi ke indeks 2D (baris, kolom) pada CPU menggunakan rumus `(indeks_cpu // jumlah_kolom, indeks_cpu % jumlah_kolom)`.

### 3. Pencetakan Hasil Indeks pada CPU
Hasil indeks nilai maksimum dan minimum pada CPU kemudian dicetak untuk analisis lebih lanjut. Pencetakan dilakukan dengan menggunakan pernyataan `print()`.

## Hasil

Dengan mengadaptasi kode untuk beroperasi pada CPU, berhasil dilakukan pencarian indeks nilai maksimum dan minimum dari tensor hasil operasi perkalian matriks pada CPU. Informasi ini memberikan wawasan tentang lokasi spesifik dalam tensor yang memiliki nilai ekstrem, yang dapat berguna untuk analisis lebih lanjut.


# **Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.**

In [20]:
import torch

# Set the random seed
torch.manual_seed(7)

# Create a random tensor with shape (1, 1, 1, 10)
random_tensor = torch.rand(1, 1, 1, 10)

# Remove all 1 dimensions to get a tensor of shape (10)
reshaped_tensor = random_tensor.squeeze()

# Print the first tensor and its shape
print("Original Tensor:")
print(random_tensor)
print("Shape:", random_tensor.shape)

# Print the second tensor and its shape
print("\nReshaped Tensor:")
print(reshaped_tensor)
print("Shape:", reshaped_tensor.shape)


Original Tensor:
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Shape: torch.Size([1, 1, 1, 10])

Reshaped Tensor:
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Shape: torch.Size([10])


# Penciptaan dan Pengubahan Bentuk Tensor dengan PyTorch

Penelitian ini melibatkan penciptaan dan pengubahan bentuk tensor menggunakan PyTorch. Langkah-langkah eksperimental dijelaskan sebagai berikut:

## Metode

### 1. Penetapan Seed Acak
Seed acak ditetapkan ke nilai 7 menggunakan fungsi `torch.manual_seed(7)` untuk memastikan reproduktibilitas nilai acak.

### 2. Pembuatan Tensor Acak Awal
Tensor acak awal dengan bentuk (1, 1, 1, 10) dibuat menggunakan fungsi `torch.rand(1, 1, 1, 10)`.

### 3. Penghapusan Dimensi dengan Nilai 1
Selanjutnya, dimensi dengan nilai 1 dihapus menggunakan fungsi `squeeze()`, sehingga mendapatkan tensor dengan bentuk (10).

### 4. Pencetakan Tensor Pertama dan Kedua
Tensor pertama (tensor acak awal) dan tensor kedua (tensor setelah diubah bentuk) beserta bentuk masing-masing dicetak untuk analisis lebih lanjut.
